# Generated by Django 5.1.3 on 2025-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_donor_founder_missionvision_schoolprofile_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mangment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Donor/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donor',
                'ordering': ['id'],
            },
        ),
    ]
