# Generated by Django 5.1.3 on 2025-09-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_mangment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mangment',
            new_name='Management',
        ),
    ]
