# Generated by Django 5.1.3 on 2025-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_mangment_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantHeadmasterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='assistant_headmaster_messages/')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': "Assistant Headmaster's Message",
            },
        ),
        migrations.CreateModel(
            name='HeadmasterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='headmaster_messages/')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': "Headmaster's Message",
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='welcome_messages/')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Welcome Messages',
            },
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ['id'], 'verbose_name': 'Management', 'verbose_name_plural': 'Management'},
        ),
    ]
