# Generated by Django 5.2.5 on 2025-09-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_assistantheadmastermessage_headmastermessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Join Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
    ]
