# Generated by Django 5.1.3 on 2025-09-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_student_alter_examresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroutine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='class_routines/'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='day',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
