# Generated by Django 5.1.3 on 2025-09-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_classroutine_image_alter_classroutine_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('awarded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_awarded', models.DateField()),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Achievement',
                'verbose_name_plural': 'School Achievements',
                'ordering': ['-year', '-date_awarded'],
            },
        ),
    ]
