# Generated by Django 5.1.3 on 2025-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_examroutine_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCircular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='admission_circulars/')),
                ('document', models.FileField(blank=True, null=True, upload_to='admission_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission Circular',
                'verbose_name_plural': 'Admission Circulars',
                'ordering': ['-created_at'],
            },
        ),
    ]
