# Generated by Django 5.1.3 on 2025-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_admissioncircular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospectus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('class_name', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=10)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prospectus_images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='prospectus_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prospectus',
                'verbose_name_plural': 'Prospectuses',
                'ordering': ['-year', 'class_name', 'title'],
            },
        ),
    ]
