# Generated by Django 5.1.3 on 2025-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
