# Generated by Django 5.2.5 on 2026-03-29 05:54

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('batch', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)])),
                ('current_location', django_countries.fields.CountryField(max_length=2)),
                ('whats_app_no', models.CharField(max_length=15)),
                ('occupation', models.IntegerField(choices=[(1, 'Business'), (2, 'Job'), (3, 'Farmer'), (4, 'Freelancer')])),
                ('last_edu', models.IntegerField(choices=[(1, 'SSC'), (2, 'HSC'), (3, 'BSC'), (4, 'MSC'), (5, 'PhD')])),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.village')),
            ],
        ),
    ]
