# Generated by Django 5.2.5 on 2026-03-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_village_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
