# Generated by Django 5.2.5 on 2026-03-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_studentregistration_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='marrital_status',
            field=models.IntegerField(choices=[(1, 'Married'), (2, 'Unmarried')], null=True),
        ),
    ]
