# Generated by Django 5.2.5 on 2026-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_studentregistration_marrital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='is_whatsapp',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
    ]
