# Generated by Django 5.2.5 on 2026-03-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_studentregistration_is_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='whats_app_no',
            new_name='bd_no',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='abroad_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='marrital_status',
            field=models.IntegerField(choices=[(1, 'Married'), (2, 'Unmarried'), (2, 'Divorced')], null=True),
        ),
    ]
