# Generated by Django 5.2.5 on 2026-03-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_rename_whats_app_no_studentregistration_bd_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.IntegerField(choices=[(1, 'পুরুষ'), (2, 'মহিলা'), (3, 'অন্যান্য')]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='is_whatsapp',
            field=models.IntegerField(choices=[(1, 'হ্যাঁ'), (2, 'না')], null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='last_edu',
            field=models.IntegerField(choices=[(1, 'এসএসসি'), (2, 'এইচএসসি'), (3, 'বিএসসি'), (4, 'এমএসসি'), (5, 'পিএইচডি')]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='marrital_status',
            field=models.IntegerField(choices=[(1, 'অবিবাহিত'), (2, 'বিবাহিত'), (3, 'তালাকপ্রাপ্ত')], null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'ব্যবসা'), (2, 'চাকরি'), (3, 'কৃষক'), (4, 'ফ্রিল্যান্সার')]),
        ),
    ]
