# Generated by Django 5.2.5 on 2026-04-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_studentregistration_student_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='abroad_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='batch',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.IntegerField(choices=[(1, 'পুরুষ'), (2, 'মহিলা'), (3, 'অন্যান্য')], null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='last_edu',
            field=models.IntegerField(choices=[(1, 'এসএসসি'), (2, 'এইচএসসি'), (3, 'বিএসসি'), (4, 'এমএসসি'), (5, 'পিএইচডি')], null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'কৃষক'), (2, 'চাকরি'), (3, 'ব্যবসা'), (4, 'ফ্রিল্যান্সার')], null=True),
        ),
    ]
