# Generated by Django 5.2.5 on 2026-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_remove_studentregistration_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='is_no_hide',
            field=models.IntegerField(choices=[(1, 'হ্যাঁ'), (2, 'না')], null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='last_edu',
            field=models.IntegerField(choices=[(1, 'SSC'), (2, 'HSC'), (3, 'BSc'), (4, 'MSc'), (5, 'Phd')], null=True),
        ),
    ]
