# Generated by Django 5.2.5 on 2026-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_album_alter_gallery_options_remove_gallery_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
