# Generated by Django 5.2.5 on 2026-04-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_alter_album_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='is_whatsapp',
            new_name='is_whatsapp_abroad',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='is_whatsapp_bd',
            field=models.IntegerField(choices=[(1, 'হ্যাঁ'), (2, 'না')], null=True),
        ),
    ]
