# Generated by Django 5.2.5 on 2026-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_edu',
            field=models.IntegerField(choices=[(1, 'SSC'), (2, 'HSC'), (3, 'BSc'), (4, 'MSc'), (5, 'Phd')], null=True),
        ),
    ]
