# Generated by Django 5.2.5 on 2026-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0028_teacher_last_edu"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissioncircular",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admissioncircular",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admissioncircular",
            name="title_bn",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="admissioncircular",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="admissionresult",
            name="status_bn",
            field=models.CharField(
                choices=[
                    ("Passed", "Passed"),
                    ("Failed", "Failed"),
                    ("Waiting", "Waiting"),
                ],
                default="Waiting",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admissionresult",
            name="status_en",
            field=models.CharField(
                choices=[
                    ("Passed", "Passed"),
                    ("Failed", "Failed"),
                    ("Waiting", "Waiting"),
                ],
                default="Waiting",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admissionresult",
            name="student_name_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="admissionresult",
            name="student_name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="title_bn",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="album",
            name="title_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="assistantheadmastermessage",
            name="message_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="assistantheadmastermessage",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="assistantheadmastermessage",
            name="title_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="assistantheadmastermessage",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="classroutine",
            name="subject_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="classroutine",
            name="subject_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="description_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="name_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="examresult",
            name="subject_bn",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="examresult",
            name="subject_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="category_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="category_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="location_bn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="location_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="title_bn",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="founder",
            name="description_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="founder",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="founder",
            name="name_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="founder",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="headmastermessage",
            name="message_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="headmastermessage",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="headmastermessage",
            name="title_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="headmastermessage",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="description_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="name_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionvision",
            name="mission_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="missionvision",
            name="mission_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="missionvision",
            name="vision_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="missionvision",
            name="vision_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="title_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ourhistory",
            name="content_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ourhistory",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ourhistory",
            name="title_bn",
            field=models.CharField(
                default="History Of Felna High School", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="ourhistory",
            name="title_en",
            field=models.CharField(
                default="History Of Felna High School", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="prospectus",
            name="title_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prospectus",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolachievement",
            name="awarded_by_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolachievement",
            name="awarded_by_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolachievement",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolachievement",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolachievement",
            name="title_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolachievement",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="address_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="address_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="class_room_info_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="class_room_info_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="contact_number_bn",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="contact_number_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="email_bn",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="email_en",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="principal_name_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="principal_name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="school_name_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="school_name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="web_address_bn",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="web_address_en",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slider",
            name="caption_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slider",
            name="caption_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slider",
            name="headline_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="slider",
            name="headline_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="address_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="address_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="name_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="bio_bn",
            field=models.TextField(blank=True, null=True, verbose_name="Biography"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="bio_en",
            field=models.TextField(blank=True, null=True, verbose_name="Biography"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="designation_bn",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Designation"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="designation_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Designation"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name_bn",
            field=models.CharField(max_length=150, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name_en",
            field=models.CharField(max_length=150, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject_bn",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Subject"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Subject"
            ),
        ),
        migrations.AddField(
            model_name="welcomemessage",
            name="message_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="welcomemessage",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="welcomemessage",
            name="title_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="welcomemessage",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
