# Generated by Django 5.2.5 on 2026-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0029_admissioncircular_description_bn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissioncircular",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="admissioncircular",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="admissionresult",
            name="status_bn",
        ),
        migrations.RemoveField(
            model_name="admissionresult",
            name="status_en",
        ),
        migrations.RemoveField(
            model_name="admissionresult",
            name="student_name_en",
        ),
        migrations.RemoveField(
            model_name="album",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="album",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="assistantheadmastermessage",
            name="message_en",
        ),
        migrations.RemoveField(
            model_name="assistantheadmastermessage",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="classroutine",
            name="subject_en",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="examresult",
            name="subject_en",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="category_en",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="location_en",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="founder",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="founder",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="headmastermessage",
            name="message_en",
        ),
        migrations.RemoveField(
            model_name="headmastermessage",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="management",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="management",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="missionvision",
            name="mission_en",
        ),
        migrations.RemoveField(
            model_name="missionvision",
            name="vision_en",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="ourhistory",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="ourhistory",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="prospectus",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="schoolachievement",
            name="awarded_by_en",
        ),
        migrations.RemoveField(
            model_name="schoolachievement",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="schoolachievement",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="address_en",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="class_room_info_en",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="contact_number_bn",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="contact_number_en",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="email_bn",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="email_en",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="principal_name_en",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="school_name_en",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="web_address_bn",
        ),
        migrations.RemoveField(
            model_name="schoolprofile",
            name="web_address_en",
        ),
        migrations.RemoveField(
            model_name="slider",
            name="caption_en",
        ),
        migrations.RemoveField(
            model_name="slider",
            name="headline_en",
        ),
        migrations.RemoveField(
            model_name="student",
            name="address_en",
        ),
        migrations.RemoveField(
            model_name="student",
            name="guardian_name_en",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="bio_en",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="designation_en",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subject_en",
        ),
        migrations.RemoveField(
            model_name="welcomemessage",
            name="message_en",
        ),
        migrations.RemoveField(
            model_name="welcomemessage",
            name="title_en",
        ),
        migrations.AlterField(
            model_name="admissioncircular",
            name="title_bn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="admissionresult",
            name="student_name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="title_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="assistantheadmastermessage",
            name="message_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assistantheadmastermessage",
            name="title_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="subject_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="title_bn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="founder",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="founder",
            name="name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="headmastermessage",
            name="message_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="headmastermessage",
            name="title_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="missionvision",
            name="mission_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="missionvision",
            name="vision_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ourhistory",
            name="content_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ourhistory",
            name="title_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="prospectus",
            name="title_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="schoolachievement",
            name="title_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="address_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="principal_name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="school_name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="headline_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="bio_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="designation_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name_bn",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="welcomemessage",
            name="message_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="welcomemessage",
            name="title_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
