# Generated by Django 5.2.5 on 2026-04-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0031_remove_admissioncircular_description_bn_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ourhistory",
            options={
                "verbose_name": "Our History",
                "verbose_name_plural": "Our History",
            },
        ),
    ]
