# Generated by Django 5.2.5 on 2026-04-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0032_alter_ourhistory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ourhistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Our History",
                "verbose_name_plural": "Our History",
            },
        ),
        migrations.AddField(
            model_name="studentregistration",
            name="facebook_profile",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="studentregistration",
            name="student_bio",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
