# Generated by Django 5.2.5 on 2026-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_alter_ourhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
