# Generated by Django 5.2.5 on 2026-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_studentregistration_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
