# Generated by Django 5.2.5 on 2026-04-12 08:44

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_alter_studentregistration_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='job_location',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'কৃষক'), (2, 'চাকরি'), (3, 'ব্যবসা'), (4, 'বেকার'), (4, 'ফ্রিল্যান্সার')], null=True),
        ),
    ]
