# Generated by Django 5.2.5 on 2026-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_studentregistration_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='job_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'কৃষক'), (2, 'চাকরি'), (3, 'ব্যবসা'), (4, 'ফ্রিল্যান্সার'), (5, 'বেকার')], null=True),
        ),
    ]
