# Generated by Django 5.2.5 on 2026-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_studentregistration_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='is_verified',
            field=models.BooleanField(choices=[(0, 'Pending'), (1, 'Accepted')]),
        ),
    ]
