# Generated by Django 5.2.5 on 2026-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_alter_studentregistration_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(default=3, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='batch',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'কৃষক'), (2, 'চাকরিজীবী'), (3, 'ব্যবসায়ী'), (4, 'ফ্রিল্যান্সার'), (5, 'বেকার')], null=True),
        ),
    ]
