# Generated by Django 5.2.5 on 2026-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_importantlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
