# Generated by Django 5.2.5 on 2026-05-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_alter_studentregistration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_edu',
            field=models.IntegerField(choices=[(1, 'MA .M.Ed'), (2, ' M.Sc. M.Ed '), (3, 'MBS. M.Ed '), (4, 'MBA. M.Ed'), (5, ' MA.B.Ed '), (6, ' M.Sc. B.Ed '), (7, 'MBS. B.Ed'), (8, 'MBA. B.Ed'), (9, 'B.Com '), (10, 'M.Com'), (11, 'BA'), (12, 'B.Sc'), (13, 'M.Sc'), (14, ' Kamil ')], null=True),
        ),
    ]
