# Generated by Django 5.2.5 on 2026-05-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_alter_teacher_options_teacher_slug_alter_teacher_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='News Location', max_length=150)),
                ('category', models.CharField(default='News Category', max_length=150)),
                ('title', models.CharField(default='News Title', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='news/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
