# Generated by Django 5.2.5 on 2026-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_video_delete_videogallery_delete_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('tender_file', models.FileField(blank=True, null=True, upload_to='tenders/')),
                ('publish_date', models.DateField()),
                ('last_submission_date', models.DateField()),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
