# Generated by Django 5.2.5 on 2026-05-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
        migrations.AddField(
            model_name='teacher',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Retired'), (3, 'Transferred')], default=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_edu',
            field=models.IntegerField(blank=True, choices=[(1, 'MA M.Ed'), (2, 'M.Sc M.Ed'), (3, 'MBS M.Ed'), (4, 'MBA M.Ed'), (5, 'MA B.Ed'), (6, 'M.Sc B.Ed'), (7, 'MBS B.Ed'), (8, 'MBA B.Ed'), (9, 'B.Com'), (10, 'M.Com'), (11, 'BA'), (12, 'B.Sc'), (13, 'M.Sc'), (14, 'Kamil')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.IntegerField(blank=True, choices=[(1, 'Accounting'), (2, 'Biology'), (3, 'Math'), (4, 'Library Science'), (5, 'English'), (6, 'Agriculture'), (7, 'Bangladesh and Global Studies'), (8, 'Islam and Moral Education')], null=True),
        ),
    ]
