# Generated by Django 5.2.5 on 2026-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_remove_teacher_is_active_teacher_leave_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[(1, 'Head Teacher'), (2, 'Assistant Head Teacher'), (3, 'Senior Teacher')], max_length=100),
        ),
    ]
