"""
Django settings for felna_school project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib import messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7+t6*j#i&kfmxzi!ruc&if$9suml&2p$jk+32^(tkwu*s#8*ie'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['felnahs.edu.bd', 'www.felnahs.edu.bd']

ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'school',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'dj_translation',
    'ckeditor',
]

LANGUAGES = (
    ('en', 'English'),
    ('bn', 'Bengali'),
)


LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'school.middleware.VisitorTrackingMiddleware',
]

ROOT_URLCONF = 'felna_school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'school.context_processors.notice_board',
                'school.context_processors.gallery_images',
                'school.context_processors.school_context',
                'school.context_processors.facility_titles',
                'school.context_processors.visitor_stats',
                'school.context_processors.active_menu',
                'school.context_processors.get_translations',
                'school.context_processors.alumni_students',
                'school.context_processors.top_news',
            ],
        },
    },
]

WSGI_APPLICATION = 'felna_school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# JSON Translation Settings
TRANSLATION_STORAGE = 'dj_translation.storage.JSONStorage'
TRANSLATION_JSON_PATH = BASE_DIR / 'translations'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
SASS_PROCESSOR_ROOT = BASE_DIR / 'static/sass'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Felna High School Admin",
    "SITE_HEADER": "Felna High School",
    "SITE_SYMBOL": "school", 

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,

        "navigation": [

            {
                "title": "Home Page",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "Home Slider", "icon": "imagesmode", "link": "/admin/school/slider/"},
                    {"title": "About Institute", "icon": "chat", "link": "/admin/school/welcomemessage/"},
                ],
            },

            {
                "title": "Teachers",
                "separator": True,
                "items": [
                    {"title": "Teacher's & Staffs", "icon": "person_pin", "link": "/admin/school/teacher/"},
                ],
            },

            {
                "title": "Academics",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "Student List", "icon": "people", "link": "/admin/school/student/"},
                ],
            },

            {
                "title": "Administration",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": "School Profile",
                        "icon": "domain",
                        "link": "/admin/school/schoolprofile/",
                    },
                    {
                        "title": "Official Notices",
                        "icon": "notifications",
                        "link": "/admin/school/notice/",
                    },
                    {
                        "title": "News",
                        "icon": "newspaper",
                        "link": "/admin/school/news/",
                    },
                    {
                        "title": "Video",
                        "icon": "newspaper",
                        "link": "/admin/school/video/",
                    },
                    {
                        "title": "Top News",
                        "icon": "campaign",
                        "link": "/admin/school/topnews/",
                    },
                ],
            },

            {
                "title": "System Control",
                "collapsible": True,
                "items": [
                    {"title": "User Accounts", "icon": "admin_panel_settings", "link": "/admin/auth/user/"},
                ],
            },
        ],
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Configuration
EMAIL_HOST = 'mail.felnahs.edu.bd'  # সঠিক SMTP সার্ভার
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

# Authentication
EMAIL_HOST_USER = 'felnahs@felnahs.edu.bd'
EMAIL_HOST_PASSWORD = 'felnahs1993@_'

# Default Sender
DEFAULT_FROM_EMAIL = 'Felna High School <felnahs@felnahs.edu.bd>'
SERVER_EMAIL = EMAIL_HOST_USER
