"""
Django settings for felna_school project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib import messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7+t6*j#i&kfmxzi!ruc&if$9suml&2p$jk+32^(tkwu*s#8*ie'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['felnahs.edu.bd', 'www.felnahs.edu.bd']

ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'school',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'dj_translation',
    'ckeditor',
]

LANGUAGES = (
    ('en', 'English'),
    ('bn', 'Bengali'),
)


LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'school.middleware.VisitorTrackingMiddleware',
]

ROOT_URLCONF = 'felna_school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'school.context_processors.notice_board',
                'school.context_processors.gallery_images',
                'school.context_processors.school_context',
                'school.context_processors.facility_titles',
                'school.context_processors.visitor_stats',
                'school.context_processors.active_menu',
                'school.context_processors.get_translations',
                'school.context_processors.alumni_students',
            ],
        },
    },
]

WSGI_APPLICATION = 'felna_school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# JSON Translation Settings
TRANSLATION_STORAGE = 'dj_translation.storage.JSONStorage'
TRANSLATION_JSON_PATH = BASE_DIR / 'translations'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
SASS_PROCESSOR_ROOT = BASE_DIR / 'static/sass'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Felna High School Admin",
    "SITE_HEADER": "Felna High School",
    "SITE_SYMBOL": "school", 
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_USERNAME": True,
    "SHOW_AVATAR": True,
    
    "COLORS": {
        "primary": {
            "50": "238 242 255", "100": "224 231 255", "200": "199 210 254",
            "300": "165 180 252", "400": "129 140 248", "500": "99 102 241",
            "600": "79 70 229", "700": "67 56 202", "800": "55 48 163",
            "900": "49 46 129", "950": "30 27 75",
        },
    },

    "USER_MENU": [
        {
            "title": "My Profile",
            "link": "/admin/auth/user/",
            "icon": "person",
        },
        {
            "title": "Log Out",
            "link": "/admin/logout/",
            "icon": "logout",
        },
    ],
        
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, 
        "navigation": [
            # {
            #     "title": "Main Dashboard",
            #     "separator": True,
            #     "items": [
            #         {"title": "Overview", "icon": "dashboard", "link": reverse_lazy("admin:index")},
            #     ],
            # },
            {
                "title": "Home Page",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "Home Slider", "icon": "imagesmode", "link": "/admin/school/slider/"}, 
                    {"title": "About Institute", "icon": "chat", "link": "/admin/school/welcomemessage/"},
                ],
            },
            {
                "title": "Committe Member",
                "separator": True,  
                "items": [
                    {"title": "Management", "icon": "manage_accounts", "link": "/admin/school/management/"},
                ],
            },
            {
                "title": "Teachers",
                "separator": True,  
                "items": [
                    {"title": "Teacher's & Staffs", "icon": "person_pin", "link": "/admin/school/teacher/"},
                ],
            },
            {
                "title": "Gallery",
                "collapsible": True,
                "separator": True,  
                "items": [
                    {"title": "Album", "icon": "photo_library", "link": "/admin/school/album/"},
                    {"title": "Photo Gallery", "icon": "photo_library", "link": "/admin/school/gallery/"},
                ],
            },
            {
                "title": "Introduction",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "History", "icon": "history", "link": "/admin/school/ourhistory/"},
                    {"title": "Mission & Vision", "icon": "flag", "link": "/admin/school/missionvision/"},
                    {"title": "Achievements", "icon": "military_tech", "link": "/admin/school/schoolachievement/"},
                ],
            },
            {
                "title": "Academics",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Student List", "icon": "people", "link": "/admin/school/student/"},
                    {"title": "Class Routine", "icon": "calendar_month", "link": "/admin/school/classroutine/"},
                    {"title": "Syllabus", "icon": "description", "link": "/admin/school/syllabus/"},
                    {"title": "Exam Routine", "icon": "schedule", "link": "/admin/school/examroutine/"},
                ],
            },
            {
                "title": "Result",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Exam Results", "icon": "grade", "link": "/admin/school/examresult/"},
                ],
            },
            {
                "title": "Admission Information",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "Admission Circular", "icon": "campaign", "link": "/admin/school/admissioncircular/"},
                    {"title": "Prospectus", "icon": "menu_book", "link": "/admin/school/prospectus/"},
                    {"title": "Admission Results", "icon": "assignment_turned_in", "link": "/admin/school/admissionresult/"},
                ],
            },
            {
                "title": "Facilities",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "Facilities", "icon": "apartment", "link": "/admin/school/facility/"},
                ],
            },
            {
                "title": "Board Permission",
                "collapsible": True,
                "separator": True,
                "items": [
                    # Add board permission items here if needed
                ],
            },
            {
                "title": "Alumni Associations",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "Alumni Students", "icon": "how_to_reg", "link": "/admin/school/studentregistration/"},
                    {"title": "Villages", "icon": "location_city", "link": "/admin/school/village/"},
                ],
            },
            {
                "title": "Administration",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "School Profile", "icon": "domain", "link": "/admin/school/schoolprofile/"},
                    {"title": "Official Notices", "icon": "notifications", "link": "/admin/school/notice/"},
                ],
            },
            {
                "title": "Website & Media",
                "collapsible": True,
                "separator": True,  
                "items": [
                    {"title": "Founders", "icon": "workspace_premium", "link": "/admin/school/founder/"},
                    {"title": "Donors", "icon": "volunteer_activism", "link": "/admin/school/donor/"},
                ],
            },
            {
                "title": "Messages",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "Headmaster Msg", "icon": "person", "link": "/admin/school/headmastermessage/"},
                    {"title": "Asst. Headmaster", "icon": "groups", "link": "/admin/school/assistantheadmastermessage/"},
                ],
            },
            {
                "title": "System Control",
                "collapsible": True,
                "items": [
                    {"title": "User Accounts", "icon": "admin_panel_settings", "link": "/admin/auth/user/"},
                    {"title": "Visitor Logs", "icon": "visibility", "link": "/admin/school/visitor/"},
                ],
            },
        ],
    },
}